name: dev

on:
  workflow_run:
    workflows: ["pre-dev"]
    types:
      - completed

jobs:
  lint-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Lint backend
        run: |
          cd backend
          npm run lint

  lint-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Lint frontend
        run: |
          cd frontend
          npm run lint

  test-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run dev server for backend
        run: |
          cd backend
          npm run dev & sleep 10; kill $!

  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run dev server for frontend
        run: |
          cd frontend
          npm run dev & sleep 10; kill $!
