name: dev

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20
      - name: Install dependencies for backend
        run: |
          cd backend
          npm ci
        env:
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
          MONGO_URI: ${{ secrets.MONGO_URI }}
      - name: Lint backend
        run: |
          cd backend
          npm run lint
      - name: Run dev server for backend
        run: |
          cd backend
          npm run dev & sleep 10; kill $!

  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20
      - name: Install dependencies for frontend
        run: |
          cd frontend
          npm ci
      - name: Lint frontend
        run: |
          cd frontend
          npm run lint
      - name: Run dev server for frontend
        run: |
          cd frontend
          npm run dev & sleep 10; kill $!
