name: dev

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20
      - name: Install dependencies for backend
        run: |
          cd backend
          npm ci
      - name: Upload node_modules as artifact
        uses: actions/upload-artifact@v2
        with:
          name: backend-node_modules
          path: backend/node_modules

  setup-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20
      - name: Install dependencies for frontend
        run: |
          cd frontend
          npm ci
      - name: Upload node_modules as artifact
        uses: actions/upload-artifact@v2
        with:
          name: frontend-node_modules
          path: frontend/node_modules

  lint-backend:
    needs: [setup-backend]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Download node_modules artifact
        uses: actions/download-artifact@v2
        with:
          name: backend-node_modules
          path: backend
      - name: Lint backend
        run: |
          cd backend
          npm run lint

  lint-frontend:
    needs: [setup-frontend]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Download node_modules artifact
        uses: actions/download-artifact@v2
        with:
          name: frontend-node_modules
          path: frontend
      - name: Lint frontend
        run: |
          cd frontend
          npm run lint

  test-backend:
    needs: [lint-backend]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Download node_modules artifact
        uses: actions/download-artifact@v2
        with:
          name: backend-node_modules
          path: backend
      - name: Run dev server for backend
        run: |
          cd backend
          npm run dev & sleep 10; kill $!

  test-frontend:
    needs: [lint-frontend]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Download node_modules artifact
        uses: actions/download-artifact@v2
        with:
          name: frontend-node_modules
          path: frontend
      - name: Run dev server for frontend
        run: |
          cd frontend
          npm run dev & sleep 10; kill $!
