name: pre-dev
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  setup-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20
      - name: Cache npm dependencies
        uses: actions/cache@v2
        with:
          path: backend/node_modules
          key: backend-${{ runner.os }}-${{ hashFiles('backend/package-lock.json') }}
          restore-keys: |
            backend-${{ runner.os }}-
      - name: Install dependencies for backend
        run: |
          cd backend
          npm ci
  setup-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20
      - name: Cache npm dependencies
        uses: actions/cache@v2
        with:
          path: frontend/node_modules
          key: frontend-${{ runner.os }}-${{ hashFiles('frontend/package-lock.json') }}
          restore-keys: |
            frontend-${{ runner.os }}-
      - name: Install dependencies for frontend
        run: |
          cd frontend
          npm ci
